connector:
  name: K8s 3rd
  identifier: K8s_3rd
  description:
  orgIdentifier: KD
  projectIdentifier: KD_QuickStart
  type: K8sCluster
  spec:
    credential:
      type: InheritFromDelegate
    delegateSelectors:
    - kd1-gcp
